version: '3'
services:
    api:
        container_name: single_service_api
        build: .
        restart: always
        depends_on: 
            db:
                condition: service_healthy
        ports:
            - 8080:8080
        networks:
            - monolith

    db:
        container_name: single_service_db
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3308:3306"
        volumes:
            - ./data:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
        networks:
            - monolith

networks:
  monolith:
    name: "monolith-network"
