version: '3'
services:
    api:
        build: .
        restart: on-failure
        depends_on: 
            - db
        links:
            - db
        env_file: .env
        # environment: 
        #     - DB_HOST=${DB_HOST}
        #     - DB_PORT=3306
        #     - DB_NAME=${DB_NAME}
        #     - DB_USER=root
        #     - DB_PASS=${DB_PASSWORD}
        ports:
            - 8080:8080

    db:
        container_name: single_service_db
        image: 'mysql'
        environment: 
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            # - MYSQL_USER=mysql
            # - MYSQL_PASSWORD=@root
            - DATABASE_HOST=db
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        ports:
            - "3307:3306"
        volumes:
            - ./data:/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        restart: always